openapi: 3.0.0
info:
  version: 0.0.0
  title: AlgoLearn
servers:
  - url: 'http://localhost:8080'
paths:
  /user:
    get:
      summary: 'Get an array of all Users.'
      operationId: listUser
      tags:
        - User
      responses:
        '200':
          description: 'Sample response: Details about a user by ID'
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /user/{username}:
    get:
      summary: 'Get a User by username.'
      operationId: listUser
      tags:
        - User
      parameters:
        - name: username
          in: path
          description: username of the user
          required: true
          schema:
            type: string
            format: string
      responses:
        '200':
          description: 'Sample response: Details about a user by ID'
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string